### ISSUE TITLE
Extracting PDF417 from PDF

### ISSUE THREAD

**Issue by bimusiek** [rk700/PyMuPDF#101]
Hey guys, any idea how to extract PDF417 code from the pdf file?
I checked, it is not an image, just encoded directly into PDF somehow.

**Comment by JorjMcKie** [comment]
Hi,
can you send me the PDF?

If it is an inline image (i.e. an image completely defined in a `/Contents` object, without an own xref), we do not support it via `Pixmap` so far - but we do extract it via `getText("json")`.

If this is not what you are talking about and this ominous PDF417 (never heard about that!) is a stream object with an xref number, you can always extract it via `doc._getXrefStream(xref)`, giving you a decompressed stream buffer (a Python bytes object).

A PDF stream object is defined as containing the literals `stream` and `endstream` following the object definition source.

The two literals enclose zero or more bytes (potentially compressed) which constitute the stream data.

Stream objects can be of almost any type (images, fonts, embedded files, metadata, contents, even other object definitions), and the stream type need not necessarily be stated in the object source (preceding the stream).

In order to trace down the stream object type, you can try looking for references to it with some clever editor (I am using SciTE). Search for "xref 0 R" in the editor window: objects containing this are referencing the stream object and should give you a clou what type of stream you are having.

**Comment by bimusiek** [comment]
Hey @JorjMcKie 
PDF417 is just a barcode type, file is here:
![image](https://user-images.githubusercontent.com/1025588/30925569-903425cc-a3b2-11e7-9ff8-1afaf9becc8f.png)

I tried to do getText('xml'), however I did not check it with json. 
However using command line `mupdf extract` did not return me this barcode. 

For now I created a workaround where I convert the whole page to .png using Pixmap (which saves this barcode correctly) and then I scan whole page image.

**Comment by bimusiek** [comment]
Argh, it uploaded image... 

Here is pdf
[Easy Jet Boarding Pass copy.pdf](https://github.com/rk700/PyMuPDF/files/1337996/Easy.Jet.Boarding.Pass.copy.pdf)

**Comment by JorjMcKie** [comment]
I see.
My email address is [Jorj McKie](jorj.x.mckie@outlook.de) (obviously I'm German).
Please send me the PDF and let me have a look - I suspect it is a PDF inline image.

**Comment by JorjMcKie** [comment]
ah I have it sorry

**Comment by JorjMcKie** [comment]
ok, this PDF contains 1 page having 13 images, which you can list via `doc.getPageImageList(0)`. There are **no** inline images.
Every single one of these images can be extracted in a pixmap via `pix = fitz.Pixmap(doc, xref)`, using one of the 13 xref numbers of the above list.

I have done that, but none of the 13 images shows the actual barcode - one or two just the frame for it (here is "Im2"):
![im2](https://user-images.githubusercontent.com/8290722/30927183-ac66a562-a385-11e7-93eb-6a0b4ecad2d0.png)
Obviously the bar data itself is encoded as PDF operator commands:
Object id 4 is the page's content stream (24 KB decompressed). Apart from referencing the above mentioned images (format `Imx /Do`) and text definitions, it contains myriads of commands which draw short line segments. Some of these must represent the dots and stripes of the bar code.

There is no way of extracting these barcode data as an image (other than you already did).

Of course you could consider writing some program that back-compiles / de-assembles these codes into more readable data ... if you have the time.

For example, you will find `238.33 730 m 239.66 730 l 239.66 734 l 238.33 734 l ` somewhere in those 24 KB of contents. This draws 2 connected line pieces:

1. connecting points (238.33, 730) and (239.66, 730)
2. connecting points (239.66, 730) and (238.33, 734)

**Comment by JorjMcKie** [comment]
sorry - **THREE** line pieces of course.
First a horizontal piece, length 1.33, then a vertical piece, length 4, then again a horizontal piece of length 1.33 in backward direction, landing 4 pixels above the starting point.

**Comment by bimusiek** [comment]
@JorjMcKie Thanks for checking, I did not expect barcode to be coded into pdf like this 👍
