### ISSUE TITLE
NameError: name 'fitz' is not defined on WINDOWS

### ISSUE THREAD

**Issue by anair81** [rk700/PyMuPDF#103]
I downloaded and installed from the binary "pymupdf-1.11.1.0-py27-x64.zip". I was able to run setup successfully and was able to generate the pyd files in (env)\Lib\site-packages\fitz folder. The trouble is I can use the fitz module if I run from the fitz folder:-

(env)\Lib\site-packages\fitz>python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import fitz

However, if I jump into another folder the import completely fails,

(env)\Lib\site-packages\fitz>cd ..

(env)\Lib\site-packages>python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fitz\__init__.py", line 2, in <module>
    from fitz.fitz import *
  File "fitz\fitz\__init__.py", line 4, in <module>
    class M_Identity(fitz.Matrix):
NameError: name 'fitz' is not defined

Any ideas on what could be going wrong?

Python configuration: I have a 64 bit, python 2.7 running in an anaconda environment.

Thanks!

**Comment by JorjMcKie** [comment]
Hm, I have tried to re-create your problem. Unsuccessfully: everything worked fine :-)

Here is what I did:
1. Download your ZIP file to my desktop
2. Unzip it on the desktop
3. Execute `py setup.py install`
4. Go back to Desktop and invoke interpreter (via `py.exe`, because I have all supported Pythons installed)
5. Import fitz: works fine

Here is the unzipped fitz dir layout:
![fitz-unzip-directory](https://user-images.githubusercontent.com/8290722/31459655-ce8098c6-ae91-11e7-8cc3-2a82a9396046.PNG)
... and the install / test log:
[fitz-install-log.txt](https://github.com/rk700/PyMuPDF/files/1376781/fitz-install-log.txt)

Please tell me your Windows version - I am using Windows 10 Pro x64. But I do regular basic tests on Win7 and WinXP virtual machines to make sure my `.pyd` binaries are self-sufficient ...

**Comment by JorjMcKie** [comment]
What I haven't done yet is testing PyMuPDF in virtual environments, and this is what you seem to be doing, right?

**Comment by anair81** [comment]
Yes. 

I retraced your steps and did a clean install from the binary (after unzipping to the desktop, in this case), and now I believe it is working. 

The issue was that I unzipped the "pymupdf-1.11.1.0-py27-x64.zip" into the (env)\site-packages and tried to build fitz (from the folder called fitz, which lives in (env)\site-packages). That mucked things up at my end.

Thank you. 

PS: I can update in this space, if fitz functions well with my anaconda environment.

**Comment by JorjMcKie** [comment]
Great, I'm glad you have an installation now. Welcome!

Please close this issue if you are fine for the moment - and don't hesitate to open another one with any question, feature request or whatever.

Recently, I have been focussing on extending the PDF output functions (draw commands). I will be uploading another little improvement in this area soon (support of text insertion by the `Shape` class).

We all can also expect the next MuPDF release within a month or so - they seem to follow a semi-annual schedule (April and November).
