### ISSUE TITLE
Get all rectangles in page

### ISSUE THREAD

**Issue by teny19** [rk700/PyMuPDF#106]
Is there a possibility or even a function that returns all rectangle objects of a certain page?

**Comment by JorjMcKie** [comment]
Rectangle objects may be created in more than one way. Only the most "canonical" way is easily detectable, as far as I can see now.  Detrails:

1. With "canonical" I mean the "re" oprator in PDF's operator syntax (see Adobe manual appendix A).
2. Other ways include just stroking 4 lines that happen to start and end in exactly 4 points and which are parallel to the axes. Much harder to detect, obviously. Especially because those line operators may be spread away from each other.

A solution for option 1:

`cont_list = page._getContents()` returns a list of the page's /Contents xref numbers. For each xref in this list (mostly only 1 exists, otherwise concatenate them) do `content = doc._getXrefStream(xref)`. This is a bytes object, so append `.decode()`  in Python 3 to get a string.
Then look for all `"re"` in this string. It may be enclosed by arbitrarily many white spaces, so best do a `content.split()` and look for all entries containing `"re"`.
Whenever you find such an entry, the 4 entries **before** represent floats (given as strings though) that constitute the 4 rectangle corners - in PDF logic, meaning (quote from PDF manual, p. 227):

```
"x y width height re" -  Append a rectangle to the current path as a complete subpath, with
lower-left corner ( x , y ) and dimensions width and height in user
space. The operation
x y width height re
is equivalent to:
x y m
( x + width ) y l
( x + width ) ( y + height ) l
x ( y + height ) l
h
```

There are several complications:

* If there are several xrefs in the above list, you need to concatenate the respective string, because the "re"-operator and its operands might be distributed across substrings. Therefore the concatenation.
* The y value are given in PDF coordinates, i.e. counted from page bottom.
* Once you have puzzled together rectangle coordinates from the "re" operation, you then need to look for matrices that may change the whole coordinate system (if you want to know the displayed location of the rectangle only). They are given by operation `a b c d e f cm` preceeding the `re`, where `a` through `f` are float strings and `cm` is an operator like `re`. Every matrix encountered must be multiplied to yield the actual rectangle location.

Still with me?
Then, as an example, have a look at what the PyMuPDF draw commands create as a page's /Contents object.

```
>>> import fitz
>>> doc = fitz.open()                                              # a new empty PDF
>>> page = doc.newPage()                                     # create a new empty page (A4 portrait)
>>> img = page.newShape()                                   # create a new empty shape
>>> rect = fitz.Rect(100, 100, 300, 400)
>>> matrix = fitz.Matrix(45)                                     # rotation by 45 deg. anti-clockwise
>>> pivot = rect.tl + (rect.br - rect.tl)*0.5                # rect center
>>> img.drawRect(rect)                                           # draw the rectangle
fitz.Point(100.0, 100.0)
>>> img.finish(fill = (1,1,0), morph = (pivot, matrix))   # finish shape and rotate everything of it
>>> img.commit()                                                   # that's it
>>> page._getContents()                                        # xref of page contents
[4]
>>> cont = doc._getXrefStream(4)                         # contents string (we are in Py2 here)
>>> print cont

n q     % enter new graphics context
0.707107 0.707107 -0.707107 0.707107 477.186 31.9714 cm     % rotation matrix
100 442 200 300 re     % your rect, 442 = 842 - 400 = height - y
1 w     % more drawing commands
1 J
1 j
h
0 0 0 RG      % border color (black)
1 1 0 rg     % fill color (yellow)
B
Q     % exit graphics context

>>> 
```
Please don't hesitate if there are questions.

**Comment by JorjMcKie** [comment]
Am I getting what you are asking for?
Maybe you wanted to find the rectangle hot spots pointing to a link destination? Or, similarly, annotations? These would be different things, of course ... but even more easily achievable.

**Comment by JorjMcKie** [comment]
Any reactions?
Can we close the issue?

**Comment by JorjMcKie** [comment]
I am going to close this for now.
Please don't hesitate to come back if you have more questions / concerns, whatever.

**Comment by mauera** [comment]
Hi. I've got a similar situation, but my image is not rotated. Here is some of the xref stream output: 

doc._getXrefStream(150).decode()
Out[93]: 'q Q q 0 0 576 432 re W n 1 sc 0 0 m 576 0 l 576 432 l 0 432 l h f 72 43.2\nm 518.4 43.2 l 518.4 388.8 l 72 388.8 l h f Q q 72 43.2 446.4 345.6 re W n\n1 j /Cs1 cs 0.9803922 0.5019608 0.4470588 sc 79.44 43.2 m 138.96 43.2 l 138.96\n185.1939 l 79.44 185.1939 l h B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs\n0.9803922 0.5019608 0.4470588 sc 153.84 43.2 m 213.36 43.2 l 213.36 267.0062\nl 153.84 267.0062 l h B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922\n0.5019608 0.4470588 sc 228.24 43.2 m 287.76 43.2 l 287.76 261.9474 l 228.24\n261.9474 l h B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922 0.5019608\n0.4470588 sc 302.64 43.2 m 362.16 43.2 l 362.16 216.942 l 302.64 216.942 l\nh B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922 0.5019608 0.4470588\nsc 377.04 43.2 m 436.56 43.2 l 436.56 124.6634 l 377.04 124.6634 l h B Q q\n72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922 0.5019608 0.4470588 sc 451.44\n43.2 m 510.96 43.2 l 510.96 67.44712 l 451.44 67.44712 l h B Q q 0 0 576 432\nre

This is everything up through output until there are no more 're' strings. 

There are some character strings here that I do not recognize, although I do have 6 numbers followed by a x y width height value set. Can you please help me interpret the numbers? 
Thank you. 

Allen

**Comment by JorjMcKie** [comment]
PDF coordinates normally start from (0,0) = bottom-left, whereas MuPDF counts from top-left. Therefore, drawing a `fitz.Rect(0, 0, 100, 200)` expressed in PDF syntax is `0  (page-height - 200)  100 200 re`. A little confusing at first.
You are right with the scaling matrix.

**Comment by mauera** [comment]
Thank you. I am curious about the transformations in the image xref. There are many of them...describing many different rectangles. Are these for different regions of the image? Should I only worry about the very first part which contains the image dimensions and starting point of 0,0? 
 **'q Q q 0 0 576 432 re**

**Comment by mauera** [comment]
In my original post, the xref for the image was clipped, but there is some path information before the rest of the image object (which I did not show). 

doc._getXrefStream(150).decode()
Out[93]: 'q Q q 0 0 576 432 re W n 1 sc 0 0 m 576 0 l 576 432 l 0 432 l h f 72 43.2\nm 518.4 43.2 l 518.4 388.8 l 72 388.8 l h f Q q 72 43.2 446.4 345.6 re W n\n1 j /Cs1 cs 0.9803922 0.5019608 0.4470588 sc 79.44 43.2 m 138.96 43.2 l 138.96\n185.1939 l 79.44 185.1939 l h B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs\n0.9803922 0.5019608 0.4470588 sc 153.84 43.2 m 213.36 43.2 l 213.36 267.0062\nl 153.84 267.0062 l h B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922\n0.5019608 0.4470588 sc 228.24 43.2 m 287.76 43.2 l 287.76 261.9474 l 228.24\n261.9474 l h B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922 0.5019608\n0.4470588 sc 302.64 43.2 m 362.16 43.2 l 362.16 216.942 l 302.64 216.942 l\nh B Q q 72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922 0.5019608 0.4470588\nsc 377.04 43.2 m 436.56 43.2 l 436.56 124.6634 l 377.04 124.6634 l h B Q q\n72 43.2 446.4 345.6 re W n 1 j /Cs1 cs 0.9803922 0.5019608 0.4470588 sc 451.44\n43.2 m 510.96 43.2 l 510.96 67.44712 l 451.44 67.44712 l h B Q q 0 0 576 432\nre

**Comment by JorjMcKie** [comment]
@teny19 - you may be interested to hear that there now is a way to extract lines, rectangles and more from PDF pages, see [here](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/extract-graphics).
