### ISSUE TITLE
[Request] getTextBlocks line seprated by list instead of space

### ISSUE THREAD

**Issue by thebestnom** [rk700/PyMuPDF#131]
Im using getTextBlocks and I have a problem that the line have space in it, so I need somehow to know if two words are single line or two seprate lines (im reading a xps file)

**Comment by JorjMcKie** [comment]
I assume you cannot use the "standard" `getText` method? It separates lines by newline characters.

I could change getTextBlocks output such that lines are separated by `\n` instead of by a space. Depending on the further use this may or may not be helpful.

How about introducing a new option argument e.g. `linesep` with space as default?

**Comment by thebestnom** [comment]
getText gives a non-standard list... I specifically need a by block list... a new option for separator sounds great, I would be more than happy to have it!
thank you so much!

**Comment by JorjMcKie** [comment]
Just uploaded a fix for issues #130 and #132.
As of these I have included a small change to `Page.getTextBlocks()`: lines within a block are now separated by linebreaks `\n` instead of spaces - without changing anything in the programmer API. This should address your request.
Please confirm.

**Comment by thebestnom** [comment]
I will have time to check it today, thank you!
