### ISSUE TITLE
Open PDFs without file endings

### ISSUE THREAD

**Issue by teny19** [rk700/PyMuPDF#155]
I'm trying to open pdf files with filenames e.g. 'File-123.34', but I get an error: 

>>  doc = fitz.Document(file_path)

RuntimeError: cannot find document handler for file: ...\\File-123.34

I figured out that when opening files with '.pdf' as file ending, the error is not thrown. Is there a way to bypass this or is the file ending mandatory?

**Comment by JorjMcKie** [comment]
# Some background:
The underlying C-library MuPDF does not bother analyzing file structures to determine the correct document type: you must tell it what type of document you wish to open.

# Two Solutions
1. Offer a filename with the correct ending. MuPDF will deduct the type from the extension.
2. Load the file into memory via e.g. `area = open("file-123.34", "rb").read()`, and then do `doc = fitz.open("pdf", area)`. MuPDF will determine the type from the "magic" string `"pdf"`.

Method 2 has the advantage that the original file is immediately closed again (i.e. available). If you update the document, you could even save the result with the original filename, because MuPDF will not check file endings at that point. On the other hand, incremental saves are not possible this way.

**Comment by JorjMcKie** [comment]
I should maybe add, that there do exist possibilities to develop a more flexible solution for our bindings. Please provide let me know how serious your problem is, and eventually request an enhancement.

As it looks now, an API change for the `open` method could be implemented to achieve this flexibility. Something like `doc = fitz.open(filename, type = "pdf")`, to enforce the PDF document handler to open `filename` if it has an unorthodox extension.

This would obviously have the advantage that one would not have to load the document into memory first.

**Comment by JorjMcKie** [comment]
I will include this fix with the next MuPDF release. I expect this coming during this month.
I am taking the liberty to close this issue for now.
As I said: should you have an urgent requirement beyond the circumvention I mentioned two comments earlier, please reopen the issue, or submit another one.
