### ISSUE TITLE
is it possible to make PDF or epub text selectable by changing PDFdisplay.py?

### ISSUE THREAD

**Issue by redstoneleo** [rk700/PyMuPDF#156]
For this demo 
https://github.com/rk700/PyMuPDF/blob/master/demo/PDFdisplay.py
I wonder is it possible to make PDF or epub text selectable using cursor by changing some code of it?
BTW, is it possible to use PyMuPDF to create a reader like sumatraPDF?

These are the factors I am considering whether to adopt PyMuPDF to develop my ebook reader .

**Comment by JorjMcKie** [comment]
Thanks for your interest in PyMuPDF.
In principle, yes to both questions. As you would have guessed, considerable work would be required for rebuilding the excellent SumtraPDF, though.

**Question 1 (select text with the cursor): Not very difficult to do.**
This must be achieved with the GUI manager used - wxPython in this case. You would have to display the page image using a wx.ClientDC. This will make it possible to draw things like reactangles on that display. Once done, convert the selection rectangle to a PyMuPDF `fitz.Rect`. Then extract the page's text (e.g. using `page.getTextWords()`) and return the text pieces that fall inside the rectangle.
This procedure will work for all supported document types.
For dealing with `wx.ClientDC` objects have a look at example program wxTableExtract.py.

**Question 2: Rebuild SumatraPDF**
As you probably know, things like the PDFdisplay.py script, and also the original wxPython script [pdfviewer](https://github.com/rk700/PyMuPDF/blob/master/demo/pdfviewer(wx).py) can out of the box access all MuPDF supported file types.
So, especially the latter could be used as a starting point, because it already contains zooming logic (PDFdisplay.py does not - it's not much more than a demo). Again, the vast majority of work is mastering the capabilities of your GUI manager. PyMuPDF itself should already have most of what you need.
With some minor exceptions: SumatraPDF supports slightly more eBook reader formats - not just epub. It can also display Windows CHM (compiled HTML). But if this would be your killer: put me in the loop. I could help supporting additional document types...

**Comment by redstoneleo** [comment]
@JorjMcKie Thanks for your kind help !

1. My GUI manager would be PyQt or PySide
2. I may also need docx and DjVu document types got supported in future 

I will drop you a line if I need your help, thanks again !

**Comment by Pedrexus** [comment]
Any update on DjVu support?
