### ISSUE TITLE
Question marks are displayed instead of text.

### ISSUE THREAD

**Issue by Millm** [rk700/PyMuPDF#171]
Hello. I'm trying to figure out the third day, but without result ...
There is a code:

`a = "बाह्यसम्पर्कतन्तु, आर्थिककेन्द्रत्वेन वर्तते"        # sanskrit
b = "normal ascii"                      # normal ascii
c = "sòmé lâtîn!"                       # latin-1 
e = "Euro sign €"                       # ascii and 1 unicode char
f = "测试"                               # Chinese
g = "Фёдор Михай Достоевский"      # Russian

import fitz
doc = fitz.open()
doc.insertPage(text = a, fontsize = 20)
doc.insertPage(text = b, fontsize = 20)
doc.insertPage(text = c, fontsize = 20)
doc.insertPage(text = e, fontsize = 20)
doc.insertPage(text = f, fontsize = 20)
doc.insertPage(text = g, fontsize = 20)
doc.save("PymuPDF.pdf", garbage=3)
doc.close()`

When this code is executed, we get the PDF file, in which the text is not displayed correctly. Namely, on 1, 4-6 pages the text is displayed incorrectly.
[PymuPDF.pdf](https://github.com/rk700/PyMuPDF/files/1994581/PymuPDF.pdf)
Tried to change the encodings, but because of the low experience, I do not get anything.

P.S. I ask to forgive me if I violated the order of registration of the issue, because it is not strong in English. In case of what, say and I will not disturb you.

**Comment by JorjMcKie** [comment]
Hi, no worries - you are welcome!
Some background first:
PDF accepts text differently in different places. This has nothing to do with PyMuPDF.
1. For text in metadata fields and bookmarks (i.e. outlines, table of contents, and the like), general unicode is always possible, and is also accepted by PyMuPDF. So, if you use your variables a, b, ... above for metadata, etc., everything will work as expected (hopefully).
2. Text in **page content** is handled differently by PDF! In order to use unicode signs beyond 0xFF you need to use a **font** that supports this.

Your example above should work if you use `doc.insertPage(text = ..., fontfile = ..., fontname = ..., ...)`.
Look for an appropriate fontfile on your system. Probably one with extension `.ttf`, `.otf`.

Because you did not specify any font information above, PyMuPDF assumes the builtin font "Helvetica", which only support character code up to 255 (0xFF), like the other builtin fonts, too.

**Comment by Millm** [comment]
Thank you very much! You helped me a lot! I got it right! 
I downloaded the required font, added:
`doc.insertPage(text = 'Фёдор Михайлович Достоевский', ..., fontfile = 'Font.ttf',
fontname = 'Font_name')`, And it all worked.
Thanks again!
