### ISSUE TITLE
Could we Add pdf_create_annot from MuPDF?

### ISSUE THREAD

**Issue by rbikw** [rk700/PyMuPDF#174]
Hello, I'm slightly new to python development, but would like to help add this feature.  I see in the MuPDF  
https://github.com/ArtifexSoftware/mupdf/blob/master/source/pdf/pdf-annot-edit.c

that they have pdf_create_annot, that feature would be great for potential dynamic annotations.

--Edit 
Sorry, is that being still updated with _addAnnot_FromString?
https://github.com/rk700/PyMuPDF/blob/master/fitz/fitz.py#L1262

**Comment by JorjMcKie** [comment]
Hi @rbikw -
this feature is on my longlist, too, for some time now. I agree, it would be nice to have it in PyMuPDF.
You are very welcome to help!

As per your post scriptum:
`_addAnnot_FromString` is used for re-inserting links (**not** annots in general) inside `Document` method `insertPDF`.
There is a feature in MuPDF to add / update PDF objects from provided strings. I have used it here and in some other places, too (`setToC` and `setMetadata`). It is quite handy when you want to avoid writing a lot of code in C - it allows doing stuff in Python instead. It could certainly be used to also create annotations. But that is not one of the first decisions to make.

This new feature would be quite big, so we need to decide on an approach first. There are about 20 different annot types, mostly radically different from each other. Widget annots (i.e. PDF form fields) also have a handful of subtypes (buttons, lists, text, signatures, ...), which adds complexity. We therefore need a plan, which types should be supported in a first, second, and maybe third wave.

Please let me know your thoughts and how you could help.

**Comment by rbikw** [comment]
I would love to help, I think just a basic Text Annotations, as described by PDF 32000-1:2008 in section 12.5.6.4. Are their other resource I should review before we get into more details. I truly appreciate all the great work you and the other contributors have done to port this functionality from C into python!

**Comment by JorjMcKie** [comment]
Based on your request, I have been busy adding major parts of this feature.
This is what the major part of the new release v1.13.7 (just uploaded) is about.
Please do have a look and check it out.
Of the relevant annotations (about 20, the markup types), only three are not supported, freetext is implemented with some limitations.

There are the following things left open for potential later improvements:

* Freetext annotations only support ASCII character text. This is a MuPDF restriction and I found no way to circumvent this over the last two days.
* Freetext annotation subtypes "callout" and "typewriter" are not yet supported. This is something you might want to contribute ...
* FileAttachments are not supported (you may want to contribute this).
* Ink annotations are not supported (you ?)
* Adding new Form fields is not supported. Mainly because this actually means creating a Form PDF, which I didn't figure out in those past few days.
