### ISSUE TITLE
segment fault when invoking page.getText()

### ISSUE THREAD

**Issue by chrisliu529** [rk700/PyMuPDF#177]
I met segment fault issues when upgraded from 1.12.5 to 1.13.8.

The test code worked fine in 1.12.5 but crashed for sigsegv in 1.13.8.

```
import fitz

doc = fitz.open('segv24.pdf')
print(doc)
for page in doc:
    print(page)
    print(page.getText(output='json'))
```

c1b2db94b1c42bdda189fa6d24a41d38(md5)  segv24.pdf

[segv24.pdf](https://github.com/rk700/PyMuPDF/files/2101211/segv24.pdf)

**Comment by JorjMcKie** [comment]
Found the problem.
Some background first - the JSON output has been reworked:
* There is a new output option `page.getText("dict")`, which returns the page content directly as a Python dict (i.e. no more need to use `json.loads` for this).
* The former output option "json" is now generated from that dictionary via `json.dumps(...)` for those who really need this.
* If you need the Python dictionary (which I assume you do), you should use the new "dict" option instead.

The problem is caused by an illegal font name (those should be ASCII) in your PDF, which my new output option did not handle correctly. I have developed a fix which I am going to upload during the day. It will have version number 1.13.10.

**Comment by JorjMcKie** [comment]
You can now download the new version from the repo's releases page or from PyPI.

One more note on the new DICT output of `page.getText()`:
* as mentioned before, this is the dictionary that you were getting before, when deserializing the old JSON output. It is now directly created, saving this extra `json.loads` step.
* this dictionary also contains any images on the page in their **binary format** (as a `bytes` object). You can directly work with these objects, saving the extra step of back-translating them from their former base64 encoding in JSON. I also deleted the integer key `imgtype` and replaced it with `ext`. This entry contains the correct file extension (like `"png"` or `"jpeg"`) for the respective image.

Overall I believe these changes make the DICT output a handy alternative, which also outperforms the earlier JSON version.

**Comment by JorjMcKie** [comment]
Did this solve your issue?

**Comment by JorjMcKie** [comment]
never mind, glad you got your issue solved!
