### ISSUE TITLE
Is it possible to extract svg diagrams with PyMuPDF?

### ISSUE THREAD

**Issue by DatenBergwerker** [rk700/PyMuPDF#178]
Hello,

I need to extract some diagrams / plots from some pdf papers but I am only shown 'real images' if I select the dict entries from` page.getText('dict')` with `type == 1`. It seems that I can see the axis labeling and other support information from the plots in xml and http `getText()` views, but e.g. bars from a bar chart or lines from a line plot seem not to be recognized.

Is it possible to extract svg images from PDFs?

Code so far:

```
import base64
import os

import fitz

workdir = os.getcwd()
pdf_path = os.path.join(workdir, 'pdfs')
pdfs = [os.path.join(pdf_path, pdf) for pdf in os.listdir(pdf_path)]

pdf_image_map = {}
for pdf in pdfs:
    doc = fitz.open(pdf)
    pages = doc.pageCount
    pdf_images = []
    for no in range(pages):
        pages_images = []
        page = doc.loadPage(no).getText('dict')
        page_images = [ele['image'] for ele in page['blocks'] if ele['type'] == 1]

        if page_images:
            pdf_images.append(page_images)
            pdf_name = os.path.basename(os.path.normpath(pdf))
            pdf_image_map.update({pdf_name: pdf_images})
```

PS: Great library btw!

**Comment by JorjMcKie** [comment]
Hello, first of all "danke für die Blumen". Lived in / near Frankfurt for the most time of my life.

Do you have an example file?

I probably have to disappoint you:
The `getText()` series of methods extract only either text or raster images from document (not only PDF) page content. There are separate (PDF-only) methods which extract (again only raster) images.

Vector images like SVG in PDF incarnate as a series of graphics commands in the PDF operator language (similar to PostScript), e.g.
```
% this draws a line from point (x1, y1) to point (x2, y2):
x1 y1 m
x2 y2 l

% this draws a rectangle with bottom-left point (x, y):
x y width height re
```
etc. Hard to detect, if you don't want to write your own full blown PDF parser-interpreter.

Some faint hope does exist to at least locate and embrace all those commands which make up such an image: probably the image will be "invoked" from some other operator source via a command like `/img Do`, where "/img" is a reference name to another object ("XObject") which might e.g. be your chart ...

**Comment by DatenBergwerker** [comment]
Hey Thanks for the quick reply.
I uploaded a single testpage with a figure that I do not see via `getText()`. So since vector images consists of those direct write operations it might be more feasible to try some other method to find them (like object recognition on a pdf page)? Thats too bad, I had hoped for an easy way :)

**Comment by JorjMcKie** [comment]
Good example!
A side remark first (you probably know it already):
You can find a (PDF only) page's images also via `doc.getPageImageList(page.number)`. In this list you find an entry for each image shown, together with its xref and some other info (**original** width, height, etc.). Using `doc.extractImage(xref)` delivers the image data (bytes object) and a suitable file extension.

* In this case `doc.getPageImageList(0) = []`- no images.
* looking at the page's object source in xref = 4 (got that from `doc._getPageObjNumber(0)` delivers `'<</Type/Page/MediaBox[0 0 595.91 842.74]/Parent 3 0 R/Resources<</ProcSet[/PDF/Text]/ExtGState 24 0 R/Font 25 0 R>>/Contents 5 0 R>>'`
* Now stepping through this information:
    - The `/Resources` object can contain references to all sorts of other stuff: fonts, XObjects, or yet other `/Resources` objects (they can be nested ...)
    - We find no `/XObjects`. Because images would have shown up here, any other XObject would have been at least a hint to some vector image ... but no.
* So the image we see on the page is completely made up by PDF operators in the page's `/Contents` object xref=5.
* This object's stream can be extracted via `c = doc._getXrefStream(5).decode()` (because it is a bytes object, I use `decode()` to make it a string).
* If I now remove all text from the page (by e.g. using [this ](https://github.com/JorjMcKie/PyMuPDF-Utilities/blob/master/anonymize.py) little utility) by working through this string `c`, I get a new PDF which looks like so: 
[anonymous.pdf](https://github.com/rk700/PyMuPDF/files/2111030/anonymous.pdf)

As you can see, the effect is quite radical ... too radical for your purposes, I assume.

**Comment by JorjMcKie** [comment]
Here is an example where an SVG image could be successfully traced (still with some effort though ...).
This creates the example PDF:
```python
import fitz
# make a little SVG image to show in a PDF
doc0 = fitz.open("microcosm.svg")
pdfbytes = doc0.convertToPDF()
src = fitz.open("pdf", pdfbytes)

# now the PDF that will contain the image
doc = fitz.open()
r = fitz.Rect(100, 100, 200, 200)
page = doc.newPage()
page.showPDFpage(r, src,0)
page.insertText(r.br, "description of picture to the left")
doc.save("test.pdf", expand=True)
```
And this is the outcome: 
[test.pdf](https://github.com/rk700/PyMuPDF/files/2111143/test.pdf)

I am considering adding a method similar to `doc.getPageImageList(pno)` for tracing back this type of situation ...

**Comment by DatenBergwerker** [comment]
Hey sry I've been really busy the last days. First of all thanks for your inspirations, but I fear I can't follow everything you did here (like what did fitz.Rect() do in your second example and how do you know the coordinates?).

And a slightly related question: If I can filter out svg elements by looking at `c = doc._getXrefStream(5).decode()`, xref would have to be dynamically assigned I guess, then could I also somehow relate the text drawn next to it? Via Coordinates or some other reference id? I sadly do not have any understanding of how a pdf is composed under the hood. But one idea I have might be to filter out the page styling elements (like lines for header/footer) and only keep the lines which will likely belong to a graphic. But again, I cannot really estimate how realistic this can be implemented.

**Comment by JorjMcKie** [comment]
The 2nd comment was just demonstrating how an SVG could be traced back in the ideal case.
Apparently it was obscuring things things instead of clarfying my point - sorry about that.

What I did was creating a PDF page that contains an SVG. Concrete values like the rectangle, the SVG file itself, etc. are just arbitrary and not of general significance.

The main point is that the commands creating the page contents contain a command like `/some-name Do` if an image or SVG or other PDF page is to be shown.

The xref number of the the page content commands can be found out by low-level PyMuPDF methods:
1. find the xref of the page `/Contents` object: `xreflist = page._getContents()`.
2. `xreflist` may contain multiple xref numbers, because a page can have multiple such objects. Normal case is just 1 integer, 5 in out case.
3. the above mentioned commands are contained in the "stream" of xref 5: `c = doc._getXrefStream(5)`. Which is a bytes object.

But the main points really are:
* in general there is no safe way to programmatically detect a drawing on a page. Your `testdoc.pdf` demonstrates this.
* exception cases are imaginable, but the effort is significant - the cost / benefit ratio unattractive.

**Comment by DatenBergwerker** [comment]
Thanks for all your effort in explaining this to me, I now get the problem and will have to reconsider how I want to tackle things.

**Comment by cipri-tom** [comment]
Hello,

@JorjMcKie I would have a follow up question regarding your comment:

> in general there is no safe way to programmatically detect a drawing on a page

Would you happen to have an idea how they retrieve such elements in complementary libraries like `pdfplumber` https://github.com/jsvine/pdfplumber#rect-properties ? I would like similar functionality in PyMuPDF because of its speed and, more improtantly, ability to modify the PDF file. So I would change the objects after retrieving them.

Many thanks and please forgive respawining an old thread !

**Comment by JorjMcKie** [comment]
> forgive respawining an old thread 

No problem at all! I am aware that something like that would be great to have.
I believe you are aware of the ``Page.draw*`` methods. Those guys insert elements which interest you.
The location **_where_** this insertion lands are the so-called `/Contents` objects, of which there can be any number per PDF page. Multiple of these are concatenated like strings, when a PDF viewer interprets them to render a page.
For detecting lines, rectangles, etc. programmatically, we must do what a PDF viewer does.

`/Contents` content is coded in hte PDF mini-language explained in this [manual](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf), page 985 (Operator Summary)., or more recent this [one](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf).

You will find there a list of commands like "q", "Q", (stack / unstack graphics state), "re" (draw rectangle) or "cm" (concatenate matrix to current transformation matrix).
One peculiarity is that this language **_prefixes_** a command with its arguments like ``a b c d e f cm``. The letters a thru f are the 6 matrix elements, given as float strings.
Another one is this. Take a rectangle ``x0 y0 width height re``. The x0, y0 coordinates are of course given in PDF geometry (origin (0,0) is page bottom-left) ... **_but_** previous "geometry changes" via matrix commands "cm" may have been established and must be known: the rectangle must be multiplied with the current value of the transformation matrix to get the actual position and size. The "cm" effect on the current transformation matrix is valid only with the current graphics state, given as everything wrapped by the sttring pair "q", "Q". When encountering "Q", the matrix's inverse is automatically concatenated.
A third aspect: "l", "c", "re", ... commands do not immediately draw a line / curve / rectangle, but rather add them to something called the "current path". The path is the animal that gets drawn (rather _stroked_, or _filled_). While adding objects to a path, any modifiers (given as other commands) can be given like fill or stroke color, line dashing, etc. which remain valid until overridden.

You can access the page's contents, either one by one by reading the streams of the xref numbers returned by ``page.getContents()``, or as one chunk (concatenation of multiples) ``page.readContents()``. They are ``bytes`` objects.
To help parsing, you can first execute `page.cleanContents()`, which (1) does that concatenation and (2) reformats the comman syntax such, that every command lives on its on line together with its prefixing arguments.

To help understand you best do a few draws and then see what happened to the page content:

```python
>>> import fitz
>>> doc=fitz.open()
>>> page=doc.newPage()
>>> # draw a triangle
>>> p1=fitz.Point(10, 10)
>>> p2=fitz.Point(10, 30)
>>> p3=fitz.Point(30, 10)
>>> # /Contents before (empty)
>>> print(page.readContents().decode())

>>> page.drawPolyline([p1,p2,p3], closePath=True, fill=(1,1,0), color=(0,0,1))
Point(30.0, 10.0)
>>> # we have drawn a triangle, filled yellow, blue border
>>> print(page.readContents().decode())

q  # go down one stack level
10 832 m  # start a path by goto point (10, 832)
10 812 l  # add line to (10, 812) to path
30 832 l  # add line to (30, 832) to path
h  # close subpath (= draw line to path start point (10, 832))
0 0 1 RG 1 1 0 rg B  # 3 commands: define colors and "fill & stroke"
Q  # unstack (one level up)

>>> 
```
Now reformat the contents for easier parsing - should put each command on separate line:
```python
>>> page.cleanContents()
>>> print(page.readContents().decode())
q
10 832 m
10 812 l
30 832 l
h
1 1 0 rg
0 0 1 RG
B
Q
q
Q

>>> 
```
I think you alrready see that e.g. replacing any to the 3 lines actually requires "understanding" what the whole path does before you are even close to rewriting it ... you will only find 2 line commands!

> BTW each ``page.draw`` method returns the last point (30, 10), so you can use it as the start for any next draw. This is the approach to establish a path yourself.

**Comment by cipri-tom** [comment]
Niice ! Thank you, @JorjMcKie  for the detailed explanation ! 
The in-line comments really clear out the mistery around PDF's "gibberish". That comment should be in the Readme for everyone thinking about working with PDFs. The specification seems so big and fluffy that it becomes unapproachable.

There is, indeed, a lot of work to correctly interpret these shapes. As you have previously suggested, it is probably easier to transform to SVG and then to work with that representation using an XML parser. I think I'll stick to this route 

Many thanks, again ! I owe you the best Venezuelan beer ^^ 🍻

**Comment by JorjMcKie** [comment]
> the best Venezuelan beer

Thanks a lot - however hard to do these days. And then there actually is only one beer, "Polar", or one of the many handcraft ones of course.

> SVG + XML parser

That is probably right. Fortunately, the SVG image creation from PDF pages is very good these days. If you do that, please make sure to use ``getSVGimage(text_as_path=0)``. This will include any text as text.
The default 1 will convert text to "atomic" draw commands: e.g. a "D" will become a vertical line followed by a left-open semi-circle curve, an "o" a small circle drawing etc. You see what I mean I hope.

**Comment by cipri-tom** [comment]
I see what you mean, as I was the one to propose the `text_as_path` parameter ^^. Thank you

**Comment by JorjMcKie** [comment]
Ah of course! Forgot to connect this to you.

**Comment by JorjMcKie** [comment]
BTW I am currently considering to develop an extractor. After giving it first thoughts, I decided to **_not_** return flat lists of lines, curves, rectangles, but instead leave the mapping intact between a "path" and its constituents. A PDF path is the unit that gets drawn on a page, consists of any number of lines, reacts, curves, etc., which have common properties like fill and stroke color, line width and dashing.
This approach should make it possible to modify such a path in a consistent manner. If a single line from inside such a path is required, then the last point of the previous entry is its start and the point stored with the "l" command is the end.

The whole thing now looks a lot more doable to me ...

**Comment by JorjMcKie** [comment]
I have a first cut of a solution. Maybe it saves you doing a lot of parsing work by combining SVG / XML intermediates.
[extract-draws.zip](https://github.com/pymupdf/PyMuPDF/files/5267228/extract-draws.zip)
There are 2 scripts: `extractGraphics.py` is the extractor, and `graphics-test.py` a test script.

The test script accepts a PDF name in the command line and extracts the graphics from page 0 (can be changed of course) by using the imported `extractGraphics`.
It the creates a new PDF with an equal-sized page and applies those graphics on the new page.
Should give you some clue what information is extracted and how it can be used.

At some time I will publish this as  a general PyMuPDF feature.

**Comment by JorjMcKie** [comment]
It may be obvious, but let me mention that this returned list of draw paths can also be used to create lists of all lines, rectangles and curves on the page, and make any calculations of the areas covered by a path or any of its elements, etc.

**Comment by JorjMcKie** [comment]
I just published a better version [here](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/extract-graphics).

**Comment by gitfabianmeyer** [comment]
Hi @JorjMcKie , your link is not working anymore, but I'm very interested in the better version, any hints where to find it? Thanks in advance

**Comment by JorjMcKie** [comment]
@gitfabianmeyer - extraction of draw / graphics commands from any page (PDF, SVG, ... any MuPDF-supported document) is now a standard feature of PyMuPDF: `Page.get_drawings()`. See the documentation.
There also is an example script included in the "Recipes" section there: https://pymupdf.readthedocs.io/en/latest/faq.html#drawing-and-graphics.

**Comment by wingbroken** [comment]
> @gitfabianmeyer - extraction of draw / graphics commands from any page (PDF, SVG, ... any MuPDF-supported document) is now a standard feature of PyMuPDF: `Page.get_drawings()`. See the documentation.
> There also is an example script included in the "Recipes" section there: https://pymupdf.readthedocs.io/en/latest/faq.html#drawing-and-graphics.

Hi Jorj, now with get_drawings() it is quite convinient to extract all vector graphics, but how can I save each of the graphics separately to an image? I tried to analyze the underlying data object, but cant tell where is the beginning and end of a graphic, if there are multiple graphics in one page.
Million thx in advance!

**Comment by JorjMcKie** [comment]
> tell where is the beginning and end of a graphic

You are not the first one asking this. There is no failsafe way, because the PDF creator might have done all sorts of dirty things. So you are left to your own wits.
If have recently developed a little script with the following logic:
* every drawing / "path" in list `page.get_drawings()` covers a rectangle stored in `path["rect"]`.
* walk through the list of these rectangles and join those which have a non-empty intersection
* if done right, you will end up with a smaller set of rectangles, where any two have an empty intersection
* walk through the curated rectangles and use each one as the clip rectangle in `page.get_pixmap(clip=clip)`, which you can then store as an image file

Doesn't always work and also isn't bug free, but often ok ...
[path2png.zip](https://github.com/pymupdf/PyMuPDF/files/6747716/path2png.zip)

**Comment by wingbroken** [comment]
> > tell where is the beginning and end of a graphic
> 
> You are not the first one asking this. There is no failsafe way, because the PDF creator might have done all sorts of dirty things. So you are left to your own wits.
> If have recently developed a little script with the following logic:
> 
> * every drawing / "path" in list `page.get_drawings()` covers a rectangle stored in `path["rect"]`.
> * walk through the list of these rectangles and join those which have a non-empty intersection
> * if done right, you will end up with a smaller set of rectangles, where any two have an empty intersection
> * walk through the curated rectangles and use each one as the clip rectangle in `page.get_pixmap(clip=clip)`, which you can then store as an image file
> 
> Doesn't always work and also isn't bug free, but often ok ...
> [path2png.zip](https://github.com/pymupdf/PyMuPDF/files/6747716/path2png.zip)

That is super helpful, thank you very much, Jorj! I made some tiny adjustment like separate the rect when have a little intersection still for my own needs, it works!
