### ISSUE TITLE
Can't render the annotations created by PyMuPDF

### ISSUE THREAD

**Issue by TimothyZero** [rk700/PyMuPDF#185]
I have used the same code in "annot_tests.py".
```
...
r+= displ
annot = page.addCircleAnnot(r)
annot.setColors(colors)
print_descr(annot.rect, annot)

doc.save("annot-tests.pdf", clean=True,expand=True)

doc = fitz.open("annot-tests.pdf")
n = 0
page = doc.loadPage(n)
pix = page.getPixmap()
pix.writePNG("page-0.png")
```
I'd like to print the the first page but I have got this:
![page-0](https://user-images.githubusercontent.com/23183180/42417566-43d9a470-82c0-11e8-9635-ccfceee63ffc.png)
But it's pretty rendered by Adobe Acrobat DC.

**Comment by JorjMcKie** [comment]
@TimothyZero I have been waiting for this ... :-)

This is a current weakness of MuPDF:
The annotations are created with a minimum of space consumption. This leads to not initially **always** creating a so-called appearance object (`/AP`). But without such a thing, MuPDF does not render anything. Which is annoying, I agree, and I hope being changed in the future.

Not only Acrobat is gracefully stepping over this stumble stone, but also most other viewers like Foxit, Nitro, PDF-Xchange and others (also tested the Ubuntu viewer). SumatraPDF however, being based on Mupdf, shows the same picture as you posted it.

If you take a viewer that supports annot handling and make **any** dummy changes and then save the PDF, you will afterwards see what has been pictured in the doc. This is because that process updates (or creates any missing) /AP.

To some extent, I do understand MuPDF's motivation:
It's not only and simply creating an /AP object that would make a difference here. Things like line end symbols (filled or empty little rectangles, arrows, circles and what not) and others would all have to be backed by code, that creates them. Every "adult" PDF viewer however does this "on the fly" when it renders a page. One of the reasons, why the same PDF **does** look different with respect to annotations, when displayed with e.g. Acrobat or Nitro.

**Comment by TimothyZero** [comment]
Thanks a lot! 
I am trying to develop a PDF viewer based on MuPDF during this holiday for adding notes and extracting text or images (just like Kindle on PC). Maybe I should reconsider the library for rendering and editing.

**Comment by TimothyZero** [comment]
Yes, it is a big project for me to realize.
Maybe I haven't expressed myself clearly but what I actually want to do is :

 - separating annotations from the document and storing into a database
 - modifying annotations without changing the document itself
 - rendering the page and annotations independently
 - combining the two layers together

So,I'm trying to figure out how to render the annotations and add it to the page. 

I'm trying to express my purpose clearly. Forgive me if I have made any mistakes. Thanks for your help!

**Comment by JorjMcKie** [comment]
I've been working on the issue in the meantime. Now, 'Square' and 'Circle' annotations work as expected. In addition, it is possible to add 'FileAttachment' annotations.

Given this experience, it shouldn't be too hard to also include the remaining 'Line', 'PolyLine' and 'Polygon' annotation types. The drawback here are the mentioned line end symbols. This is a huge amount of work. Maybe I upload something without the line end feature.

# Reacting to you comment

* "storing annots in a database" what does that mean: their image? their definition? You can create annot pixmaps much like page pixmaps via `annot.getPixmap()`.
* You can modify almost every apsect of an annot: colors, line width, its rectangle. After a modification, the document must be saved however - there is no other way to make changes permanent.
* As I said, you can create an annot's pixmap independently from the page. But rendering a page **without** also showing the pixmap is not **directly** possible (yet). But **indirectly**, you can achieve this (see below).
* "combining the two layers" - what exactly do you mean: an option to switch annotation rendering on/off?

# Script to render a page with and without annotations
```python
>>> import fitz
>>> doc = fitz.open("new-annots.pdf")
>>> page = doc[0]
>>> pix1 = page.getPixmap(alpha=False) # page image with annots
>>>  # create a temp PDF with one page of original's dimensions
>>> tmp = fitz.open()
>>> tmppage = tmp.newPage(width = page.rect.width, height = page.rect.height)
>>> # method showPDFpage displays pages from other PDFs in current one
>>> tmppage.showPDFpage(tmppage.rect, doc, 0) # insert orig. page without annots
8
>>> pix2 = tmppage.getPixmap(alpha=False) # page image without annots
>>> # tmp PDF can now be closed / discarded
>>> pix1.writePNG("pix1.png") # write image with annots
>>> pix2.writePNG("pix2.png") # write image w/o annots
>>> 
```
## Image with annots:
![pix1](https://user-images.githubusercontent.com/8290722/42499432-c9c81f02-83fc-11e8-8192-a494d51cbae1.png)
## Image without annots:
![pix2](https://user-images.githubusercontent.com/8290722/42499481-e48ff7b0-83fc-11e8-8fa5-fa890ab21db2.png)

**Comment by JorjMcKie** [comment]
Proudly presenting my latest version enhancement. I am going to upload this as version PyMuPDF 1.13.13 during the day.
As I said, creating line end style symbols is still not supported, and maybe never will.

![grafik](https://user-images.githubusercontent.com/8290722/42509315-81551b54-8419-11e8-81ab-fa4785bb1379.png)

**Comment by JorjMcKie** [comment]
New version uploaded.

**Comment by TimothyZero** [comment]
That's cool! Thanks!
