### ISSUE TITLE
insertText(overlay=False) gives "cannot resize a buffer with shared storage" error

### ISSUE THREAD

**Issue by wave-DmP** [rk700/PyMuPDF#193]
I am trying to insert a hidden text layer of OCRed text into a pdf page for future analysis, however I am getting the following error.  The error occurs only when I add the overlay=False flag.

This may be due to my setup maybe?  In addition, is this the correct way to insert a hidden text layer?
from source fitz/utils.py/line 998: "overlay - put text in foreground or background"

Windows 10 x64, Python 3.6.5, Jupyter Notebook 5.5.0, pymupdf 1.13.15

```
<ipython-input-48-52c8f7ddb218> in analyse_pages(file, page, i, zoom, prt)
     66             pnt = fitz.Point(left, top)
     67             page.insertText(pnt, row['text'],
---> 68                             overlay=False)

~\Anaconda3\lib\site-packages\fitz\utils.py in insertText(page, point, text, fontsize, fontname, fontfile, idx, set_simple, color, rotate, morph, overlay)
   1040                         morph = morph)
   1041     if rc >= 0:
-> 1042         img.commit(overlay)
   1043     return rc
   1044 

~\Anaconda3\lib\site-packages\fitz\utils.py in commit(self, overlay)
   2720         else:                               # first one if background
   2721             xref = self.page._getContents()[0]
-> 2722             cont = self.doc._getXrefStream(xref)
   2723             cont = self.totalcont + cont    # prepend our stuff
   2724 

~\Anaconda3\lib\site-packages\fitz\fitz.py in _getXrefStream(self, xref)
   1487             raise ValueError("operation illegal for closed / encrypted doc")
   1488 
-> 1489         return _fitz.Document__getXrefStream(self, xref)
   1490 
   1491 

RuntimeError: cannot resize a buffer with shared storage
```

**Comment by JorjMcKie** [comment]
This is the correct way to store hidden text.
Let me check and see if I can reproduce the error. I have an idea about its whereabouts, and it is definitely not caused by you / your setup.

**Comment by JorjMcKie** [comment]
Hm, I did successfully inserted text on a PDF page (showing an image) in various combinations of overlay True/False.
Everything worked fine.

I did see a few "dangerous" places though, where I used "shared storage" ( = read-only storage) for the content update.

"Dangerous" in this context means, that the internal function to determine the buffer length may also try to write a \0 to the end of that (read-only) buffer.

I have modified the stuff now to only use writeable buffers when updating content streams.

Can you give an idea how urgent your issue is? I am going to include a few other things, before I upload a new version (probably tomorrow), 1.13.16.

**Comment by wave-DmP** [comment]
As before, next day is well within my timescale.

Thank you!

**Comment by JorjMcKie** [comment]
v1.13.16 is available now on GitHub and should be as well on PyPi within a minute.
Please do test the version and give feedback - as I said: I couldn't reproduce the error and had to guess what might have gone wrong in your case ...

**Comment by wave-DmP** [comment]
Just tested it (PyPI) - your fix has worked, error is gone.

Thanks again!

**Comment by JorjMcKie** [comment]
Thanks for the fedback!
