### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#20]
Hi @rk700,
after no more issues are popping up and documentation being done, I think it is time to release ...
I can do it, if you do not have the time.
Also should think about making it more "searchable", meaning:
People are looking for "PDF" or even "MuPDF", but not for "fitz", when they search a solution for accessing PDFs via Python.
I am not sure what would the best ... maybe renaming it to something like "PyMuPDF"?
And how about adding it to the Python Package Index?

**Comment by rk700** [comment]
Hi @JorjMcKie. 

Yes I agree that it's ready for release. The repo's name is changed to PyMuPDF, and the README is updated accordingly. Currently "fitz" is still kept in the code, and let's see whether it is necessary to rename it too.

As for the Python Package Index, I've never used it before. So I'll do a little research and see what it is.

**Comment by JorjMcKie** [comment]
Python Package Index = PyPI
It just crossed my mind, because it probably will generate publicity - people look there when they want Python solutions.

I will also write to this guy who made the wxPython demos. I believe he is Italian. He references python-fitz already today (version 1.2). He should be informed that there now is a great new super dooper solution called PyMuPDF on version 1.7 ...

**Comment by ousia** [comment]
@JorjMcKie, sorry for my delayed reply.

What is wrong with `python-fitz`?

I think it states clearly that it is about the Python bindings of the `fitz` library.

As comparison, there is (or at least, there was) a `python-poppler` library with Python bindings for the `poppler` library (<http://poppler.freedesktop.org/>).

I guess the issue is not the name itself, but the right description. If you allow me an example: <http://koji.fedoraproject.org/koji/buildinfo?buildID=658962>.

MuPDF is the name of the application. And if I’m not wrong, this bindings are related to the library.

**Comment by JorjMcKie** [comment]
Of course there is nothing wrong with "python-fitz" as such.
The consideration was: what keywords are people using when they want to find something that allows them to access PDF from a Python environment? Certainly it would be a combination of "PDF", "Python" and maybe "MuPDF" if they have heared about the library. Nobody has ever heared about "fitz".
So our repository name and description should include those three words: "Python", "PDF" and "MuPDF". The use of the rendering library "fitz" is no more than a technical detail and will not help us become more popular.

**Comment by ousia** [comment]
@JorjMcKie, many thanks for your reply.

I see your point. I’d say that `python-mupdf` may work (`pyPDF` is already taken).

But probably the main issue is that (Linux) distributions package it and people start using it for their projects.
