### ISSUE TITLE
Rewritten outline is displayed only by mupdf-based applications

### ISSUE THREAD

**Issue by vt220** [rk700/PyMuPDF#213]
If a new pdf file with an outline is created, the outline can be read by many pdf readers. But when outline of an existing pdf file is changed, only mupdf-based applications are able to display it. Non-mupdf based applications report that there is no outline in the document.

To reproduce the problem, take a small pdf file with an outline, for example: https://www.gnu.org/software/sed/manual/sed.pdf, and then execute the following code:

from fitz import *
doc = Document("sed.pdf")
doc.setToC(doc.getToC())
doc.save("test.pdf")

When the resulting test.pdf is opened by a mupdf-based application - for example by mupdf, mupdf-based version of zathura on linux or by Sumatra PDF on windows, the outline is displayed as expected. But when it is opened by okular, xpdf, evince, poppler-based version of zathura on linux or adobe acrobat on windows, there is no outline present

I use PyMuPDF 1.13.20 and Python 3.7.0

**Comment by JorjMcKie** [comment]
I looked at the problem:
The reason is, that I am writing the new TOC entries reusing old xref numbers as much as possible. This leads to an increase of the so-called "generation number" of any such enries. However, my changed TOC entries always refer to other entries using generation = 0. Some readers then react as you described, and won't find entries having a wrong gen#. (Not sure, since when this behaviour occurs ... used to be different in earlier MuPDF versions).

I will change my approach in the next release to always allocate new XREFs.

As a quick solution, use the ``garbage`` option in save, with a value of at least 2. So your last statement above would read ``doc.save("test.pdf", garbage=2)``. This option will (1) garbage collect unused objects, and (2) compact the XREF (all objects will then have a gen# of 0). I have successfully tested it with Adobe.

BTW, in order to recreate the TOC with full information, extract it via ``doc.getToC(False)``. This will prevent a simplified TOC version being created.

**Comment by JorjMcKie** [comment]
Further investigation revealed the following:

1. the crucial cross reference number table in PDFs can come in 2 variants: old-style or compressed in a stream.
2. if a PDF has a streamed Xref, MuPDF has some issues updating them in a way that all readers can understand (your issue).

This means that my previous assumption about what should solve the problem was **not correct!**

Until MuPDF fixes this issue, you should proceed as I recommended: save to a new file (no incremental update) with garbage option >= 2. This will create a new, cleaned, non-compressed XREF (and also remove any unused objects).

I will implement this into PyMuPDF: incremental update will be prevented if there is a streamed XREF table. Saves to a new file will always also reorganize the XREF table if it was a streamed one.

Can you please confirm that using the garbage option works for you?

**Comment by vt220** [comment]
Yes, I can confirm that using the garbage option solves the problem for me.
Do you intend to report the MuPDF issue to the owners or would you like me to report it?

**Comment by JorjMcKie** [comment]
Please go ahead and submit an issue. And also please take me on CC. I will support your submission with more data.

The reason for this approach:
I just found another bug in 32bit MuPDF only, concerning document conversion to PDF, and I would like a larger population of bug submitters appear there.

As far as you and I are concerned with this issue: OK to close?

**Comment by vt220** [comment]
Since there is a workaround, and since you are going to implement a workaround to solve the problem even when an optional save()'s parameter is not used, then sure, the problem is resolved.

A question about the problem itself (for a bug report to mupdf): when you mentioned a problem with a streamed xref, did you mean the same xref mentioned in a section 7.5.4 of the PDF's specs? If yes, then the problem is not quite clear to me - in the reproduction of the problem above I see that neither the xref itself nor the document's outline in the resulting file 'test.pdf' are streams, but nonetheless the problem exists. So it seems that the problem is not just due to the streamed xref. What I am missing here?

**Comment by JorjMcKie** [comment]
The XREF of ``sed.pdf`` is encoded in object 1507 and looks like this:

![grafik](https://user-images.githubusercontent.com/8290722/47637175-3ee6e580-db31-11e8-92c3-3dee7c99d70e.png)

It contains pointers to the info (1506) and root (1505) objects. The binary data following the keyword ``stream`` are the encoded xref numbers of the PDF. Without requesting a new XREF section being built (via that garbage option), MuPDF tries to maintain this object number 1507 and its stream. Obviously in a manner that some readers do not understand.

However, when using `garbage=2` (or command `mutool clean -gg sed.pdf`), the XREF section will be recreated in old-style and look like this: 

![grafik](https://user-images.githubusercontent.com/8290722/47638380-c8e47d80-db34-11e8-8df7-721f0a25049c.png)

The file end with its trailer will also look conventional again:

![grafik](https://user-images.githubusercontent.com/8290722/47638938-71471180-db36-11e8-991b-cfa3295b611e.png)

**Comment by vt220** [comment]
But this is exactly the point: in 'test.pdf' from my example above which shows the problem xref is *also* created in old-style, but the outline is still not readable by other pdf readers.

**Comment by JorjMcKie** [comment]
You are right. There are multiple issues -- not just the compressed XREF.
The outline header (an object of type `/Outlines`) is not correctly updated either. It should point to the new outline objects, but it still contains pointers to the old (deleted) ones.

I don't know why this is so. Maybe because this outline header object is itself contained in another stream object containing many other object definitions in compressed form.

When I replace table of contents, I do this:

1. delete all old outline objects
2. delete the `/First`, `/Last` and `/Count` entries in the outline header
3. insert my new outline objects
4. insert keys and values for `/First`, `/Last` and `/Count` in the outline header

Points 2. and 4. did not occur here. Maybe my logic should be a little more radical like this:

1. delete all old outline objects
2. **delete the outline header**
3. insert my new outline objects
4. **insert a new outline header**

Let me try how this works out. Once I know the problem scope a little better, I will come back.
Currently we have no real basis to submit something to MuPDF.

**Comment by JorjMcKie** [comment]
Ha! It worked! Thank you for your input and being so insistent ...
With the change indicated above, the following things happen:

1. At **normal** save to new file (**no options given** like in your snippet):
    * all my readers, including Adobe, correctly recognize the new TOC
    * the PDF's object definitions are now all decompressed (i.e. no more `/Objstm` type objects present)
    * the XREF table is converted to old-style

2. At **incremental** save:
    * again, all readers recognize the new TOC
    * the `/Root` and `/Outlines` objects appear updated in the delta, together with the new outline items
    * the XREF table **remains a stream** and also appears updated in the delta

So everything works as expected, no special behaviour required. Probably fair to say, the error was more on my side. At least there is no basis to submit a bug to MuPDF - they would always argue that I should do what I am now doing.

I will implement this version for the new release v1.14.0.
If you want, I can also publish a hotfix v1.13.21 - please let me know.
