### ISSUE TITLE
extraction through json is failing for my pdf

### ISSUE THREAD

**Issue by satyaaditya** [rk700/PyMuPDF#217]
code : 
`document = fitz.Document('Article.pdf')`
`page = document[0]`
`obj1 = page.getText('json')`
`print obj1`

error:
`error: Unable to read ICC workflow
warning: Attempt to read Output Intent failed
Traceback (most recent call last):
  File "/home/satyaadityabaratam/PycharmProjects/HTML_FAQ/PDF_Extraction/PyMuPDF.py", line 13, in <module>
    obj1 = page.getText('json')
  File "/usr/local/lib/python2.7/dist-packages/fitz/utils.py", line 129, in getText
    t = tp._extractText(f)
  File "/usr/local/lib/python2.7/dist-packages/fitz/fitz.py", line 3828, in _extractText
    val = json.dumps(val, separators=(",", ":"), default=convertb64)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte
`
pdf - 
[Article.pdf](https://github.com/rk700/PyMuPDF/files/2538539/Article.pdf)

**Comment by JorjMcKie** [comment]
Your problem should also only occur with image blocks in the dictionary. For topmost performance, I return images on a page in original binary image format.
For conversion to JSON I was intentding to use base64 encoding. But obviously this doesn't work in Python2 because that version knows no difference between `str` and `bytes`.
So what I will probably end up doing is one of the following (under Python 2 only):
1. provide images in base64 format already in the "dict" output, or
2. disable "json" output alltogether

**Comment by satyaaditya** [comment]
thank you, i upgraded to python 3 and its working now

**Comment by JorjMcKie** [comment]
Thank you for reporting this.
In fact your issue caused me to investigate other ways out. What I will be doing in the next release is creating a `bytearray` object for these images under Python 2. This allows to differentiate between image binary data and other strings in Python.
Which in turn makes it possible to recognize thse data in Python 2 as well. Now the JSON output looks equal between Py 2 and 3.
