### ISSUE TITLE
How to split a page in pdf using PyMuPDF?

### ISSUE THREAD

**Issue by satyaaditya** [rk700/PyMuPDF#219]
Hi,
Is there any way to achieve splitting  a page in the pdf using PyMuPDF, currently i am achieving it through mutool. i want to use a library instead of utility.

In docs there is documentation for splitting pdf and not individual page, how can i achieve this  through MuPdf?

**Comment by JorjMcKie** [comment]
Currently I cannot go online, but this is easily done: look at my PyMuPDF-utilities repo. You will find a script named “posterize.py”. Allows to split PDF pages in any desired way.

Von meinem iPhone gesendet

Am 09.11.2018 um 06:36 schrieb satyaaditya <notifications@github.com<mailto:notifications@github.com>>:


Hi,
Is there any way to achieve splitting a page in the pdf using PyMuPDF, currently i am achieving it through mutool. i want to use a library instead of utility.

In docs there is documentation for splitting pdf and not individual page, how can i achieve this through MuPdf?

**Comment by JorjMcKie** [comment]
no, it is here: [posterize.py](https://github.com/rk700/PyMuPDF/blob/master/examples/posterize.py)

**Comment by JorjMcKie** [comment]
Found what you where looking for?

**Comment by satyaad-kore** [comment]
`python3 posterize.py value_sheet.pdf 
Traceback (most recent call last):
  File "posterize.py", line 56, in <module>
    reuse_xref=xref)  # copy input page once only
TypeError: showPDFpage() got an unexpected keyword argument 'subrect'
`
getting an error while trying to run this script

**Comment by JorjMcKie** [comment]
``subrect` has been changed to clip` - see docu

**Comment by satyaaditya** [comment]
thanks a lot, i can make my usecase from here
