### ISSUE TITLE
can't run demo example in windows or centos

### ISSUE THREAD

**Issue by caibojun** [rk700/PyMuPDF#234]
Am I the only ONE can not run the "extract-img2.py" script under Windows or CentOS but when under Ubuntu it works , so wired!

> Traceback

 (most recent call last):
  File "C:/Users/viruser.v-desktop/Desktop/direction_detect/extract_image.py", line 111, in extract_image_test
    extract_image(pdf_path, output_dir)
  File "C:/Users/viruser.v-desktop/Desktop/direction_detect/extract_image.py", line 65, in extract_image
    text = doc._getObjectString(i)
  File "C:\Program Files\Anaconda2\lib\site-packages\fitz\fitz.py", line 1710, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Document, name)
  File "C:\Program Files\Anaconda2\lib\site-packages\fitz\fitz.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Document' object has no attribute '_getObjectString'`

**Comment by JorjMcKie** [comment]
Hi,
sorry I forgot to update documentation and the example on that:

Please use ``_getXrefString`` instead of ``_getObjectString``. They have been synonyms forever, and I have deleted one.

BTW you must be running different PyMuPDF versions in your different machines: the synonym deletion took place in the current v1.14.3.

I will update the demo script accordingly.

**Comment by caibojun** [comment]
Yes, just figured out you guys had changed the version 6 hours before, and my Ubuntu OS has installed last day,no wonder it became so wired... XD! Thank you guys!

**Comment by xiaokongkong** [comment]
if you get the error like "AttributeError: 'Document' object has no attribute '_getXrefLength'", maybe you could degrade the version of PyMuPDF to 1.16.7
