### ISSUE TITLE
Font information for page.searchFor method?

### ISSUE THREAD

**Issue by satyaaditya** [rk700/PyMuPDF#238]
From docs i could see font information can be retrieved with getFontList or getText('dict'). But is there anyway to get font of searched strings in page? if no, can you add support for it, it would be lot more helpful.

**expected scenario:**
`page.searchFor(' seach_String')`

**output:**

`[font-name, fontsize, bbox or rect]`

**Comment by JorjMcKie** [comment]
You can get this information by combining methods `page.searchFor()` and `page.getText("dict")`. Or, if you need font information rightaway, you can search your string directly in `page.getText("dict")` output (and not use searchFor at all).

You can also build your own search method based on the dict output, obviously.

Building this into `page.searchFor` would not make sense, because it can search for strings that cover more than one text span and thus can contain more than one font.

Text spans in dict output (currently) do not have a bbox. But if you use "rawdict" instead, you can build one by unifying the character bboxes contained in the span.

**Comment by satyaaditya** [comment]
yes, i can do that. 
_"   Building this into page.searchFor would not make sense, because it can search for strings that cover more than one text span and thus can contain more than one font   "_ -  yes, since searchFor method gives all occurrences with bbox, i found no harm in providing font-info also. 

Thanks, i will implement with dict and raw_dict info
