### ISSUE TITLE
annots in v1.14 - annot.setColors() not working

### ISSUE THREAD

**Issue by wave-DmP** [rk700/PyMuPDF#243]
when adding annots, I was previously making colour-code rectangles around them (including transparent stroke with None), with v1.14.x however all annot rectangles are black, is this a bug?

**Comment by JorjMcKie** [comment]
All annotations are given standard properties at creation time. Mostly (not in all cases), stroke color is black, fill color transparent, line width is 1, etc.

To achieve a different appearane, properties must be changed via methods like ``setBorder``, ``setColors`` and so on, and, most importantly, the annotation method ``update()`` **must be invoked** to make those changes effective. This is new in v1.14, and it was required because of the greatly extended annotation support implemented in the MuPDF base library.

**Comment by JorjMcKie** [comment]
You can make as many changes to an annotation as desired -- ``annot.update()`` only needs to be invoked once to apply all previous changes.

**Comment by wave-DmP** [comment]
solved, thank you! 

merry xmas!

**Comment by JorjMcKie** [comment]
Thanks for the feedback!
Merry xmas!
