### ISSUE TITLE
setRotate(), getRotate() throwing errors

### ISSUE THREAD

**Issue by wave-DmP** [rk700/PyMuPDF#249]
Hi, I'm getting the following error when executing both methods on a page object
using both page. and doc[i].

'Page' object has no attribute 'setRotate'
'Page' object has no attribute 'getRotate'

I'm trying to bulk change page orientation of a pdf

**Comment by JorjMcKie** [comment]
Hi, please use `Page.rotation` for accessing current value, and `Page.setRotation` for changing it.

Is there an error in the doc?

**Comment by wave-DmP** [comment]
it's was mentioned in the v1.9.3 wiki
https://github.com/rk700/PyMuPDF/wiki/How-to-Rotate-PDF-pages-in-a-handful-of-lines-(v1.9.3)

in addition, the page rotation recipe was empty:
https://github.com/rk700/PyMuPDF/wiki/Inserting-Pages-from-other-PDFs-(v1.9.2)

i've found it in the documentation now, thanks for clearing this up!

**Comment by JorjMcKie** [comment]
A pleasure.
To be honest, I am never quite sure if my docu is up-to-date / in sync with the software ...

**Comment by JorjMcKie** [comment]
I'll go ahead and change that WIKI

**Comment by JorjMcKie** [comment]
Done. Also deleted that empty Wiki.

A better description on how `Document.insertPDF` works can be found in https://github.com/rk700/PyMuPDF/wiki/Inserting-Pages-from-other-PDFs.

This method (as well as method `Document.convertToPDF`) has a parameter `rotate` (not `rotation`) because I felt it better expresses this being an activity. And `setRotation` would have been unduly in terms of PEP8 (camel case and what not).
