### ISSUE TITLE
fitz.Identity is not hashable in 1.9

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#53]
While `fitz.Matrix(1,1)` is hashable and can be  used as a key in dict, `fitz.Identity` is not hashable.
```py
>>> import fitz
>>> a = fitz.Matrix(1, 1)
>>> hash(a)
8757058983372
>>> hash(fitz.Identity)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'SwigPyObject'
```

**Comment by JorjMcKie** [comment]
Actually I have changed fitz.Identity in 1.9 to be truly %immutable. Before that you could manipulate it - and either cause the interpreter to crash or, even worse, to make it no longer an identity.

Any suggestions?

**Comment by mozbugbox** [comment]
subclass fitz.Matrix, Make a,b,c,d,e,f read only properties and remove preOperations of the subclass?

**Comment by JorjMcKie** [comment]
Well, exactly this SWIG wouldn't allow to do.
But I have found another way to achieve it. I am going to upload a fix during next hour.

**Comment by JorjMcKie** [comment]
Behaviour of fitz.Identity is now like this:
[Identity_fix.txt](https://github.com/rk700/PyMuPDF/files/275186/Identity_fix.txt)

**Comment by JorjMcKie** [comment]
Sorry for the confusion!
I thought I had a solution, but I don't.
What was shown in my previous post, changes not only the behaviour of ``fitz.Identity``, but also the one of **every other** matrix!

So far I am unable to define ``fitz.Identity`` as a hashable, but not modifyable ``fitz.Matrix``.
So I reverted the definition of fitz.Identity to the state of version 1.8:
It is a hashable matrix. At least on my Windows, SWIG will **not** prevent me from changing its attributes - no matter whether I use the ``%immutable`` attribute.

@rk700 , @mozbugbox : ideas what else I could try?

**Comment by mozbugbox** [comment]
I was thinking subclass Matrix in Python code, something like:
```py

class MatrixID(fitz.Matrix):
    def __init__(self):
        fitz.Matrix.__init__(self, 1, 1)
    def __setattr__(self, name, value):
        if name in "abcdef":
            raise NotImplementedError
        else:
            super().__setattr__(name, value)

```

Since the Matrix was subclassed from Python object, it should work.

The Matrix implementation in fitz/fitz.py looked complicated but the idea was straight forward.

**Comment by mozbugbox** [comment]
Or simple monkeypatch Matrix.Identity instance. But changes between python2/python3 make monkeypatching class instance even more complicated.

**Comment by JorjMcKie** [comment]
@rk700 , @mozbugbox  - thanks for help, seems to work now - testing ...

**Comment by JorjMcKie** [comment]
I just uploaded the fix alongside more changes for new functionality as requested by issue #51.

**Comment by rk700** [comment]
How about adding a `__hash__()` function to the `Matrix` class? I'm not quite sure but it might make the class hashable even if it is read-only.

**Comment by JorjMcKie** [comment]
Let me tell the full sad history:

1. In 1.8 I observed that fitz.Identity looked exactly like any fitz.Matrix with all attributes and methods. But SWIG did not prevent to do e.g. ``fitz.Identity.a = 0``! Instead, the interpreter crashed. Or, paradoxically, when adding an explicit ``%immutable``, I could successfully change attributes of it. An exception was **never** issued by SWIG (as it should have occurred).
2. To cure that, I added the following code fairly at the beginning of ``fitz.i`` - at least **before** the ``fitz.Matrix`` definition (otherwise the problem detailed under point 1 occurs again):

```
    %immutable;
    %inline %{
    const struct fz_matrix_s Identity = { 1, 0, 0, 1, 0, 0 }; 
    %}
    %mutable;
```
This made it usable as a do-nothing matrix, but it was generated by SWIG as an object of type ``SwigPyObject``, which has no ``fitz.Matrix`` attributes of course, but unfortunately issues exception ``TypeError: unhashable type: 'SwigPyObject'`` when trying ``hash(fitz.Identity)`` as @mozbugbox found out. Confusingly, this object type **does** have a ``__hash__()`` method (with a negative return value)! Here is the full output of the calamity:
```
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import fitz
>>> i = fitz.Identity
>>> type(i)
<type 'SwigPyObject'>
>>> i
<Swig Object of type 'fz_matrix_s *' at 0x0302EC38>
>>> dir(i)
['__class__', '__cmp__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__',
'__getattribute__', '__gt__', '__hash__', '__hex__', '__init__', '__int__', '__le__',
'__long__', '__lt__', '__ne__', '__new__', '__oct__', '__reduce__', '__reduce_ex__',
'__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'acquire',
'append', 'disown', 'next', 'own']
>>> hash(i)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    hash(i)
TypeError: unhashable type: 'SwigPyObject'
>>> i.__hash__()
-2144325949
>>> i.a
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    i.a
AttributeError: 'SwigPyObject' object has no attribute 'a'
>>> 
```
- We wouldn't have to discuss all this, if SWIG had behaved as expected with ``const`` / ``%immutable`` objects!
- Maybe I haven't seen a more obvious solution than we have now ... ?
