### ISSUE TITLE
Document.close() crashes after successful decryption

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#55]
@rk700 - If a document is successfully decrypted, a following ``close()`` method will reproducibly crash the interpreter - either immediately, or at the latest when the document is dropped (``doc = None``).

Can you confirm thisfor Linux as well? This is maybe "works as designed" - quite imaginable, in which case I would implement prohibiting ``close()`` after decrypts to produce a graceful exception.

**Comment by rk700** [comment]
Yes I just tried it on Mac and it did result in python crash: "pointer being freed was not allocated". I'll try it on Linux later where I can do the debug work.

**Comment by rk700** [comment]
I debug the crash on Linux. It's caused by a double free when calling `_wrap_delete_Document`. Then I notice that the `Document` has `thisown` attribute set to `False` only when it is not encrypted, which I think is the reason. So I update the code by setting `thisown` to `False` as long as the `Document` is valid, and now closing encrypted `Document` would not crash python.
