### ISSUE TITLE
Problem setting up makefile to Ubuntu-derived OS

### ISSUE THREAD

**Issue by Magistrado** [rk700/PyMuPDF#75]
I'm trying to install PyMuPDF 1.9 in a machine with Ubuntu-derived OS.  I built from sources:

I added -fPIC on the line 10: CFLAGS += -Wall -fPIC. This is in Makerules.
I set HAVE_x11=no and Have_GLFW=no.

Then, I executed:
 - make prefix=/usr/local install
 - python3.5 setup.py install

In the last command, i got the following:
recompile with -fPIC
/bin/ld -freetype',
/bin/ld -jbig2dec
/bin/ld -openjp2
It cannot link with...

Please, help me to set up the makefile.

**Comment by JorjMcKie** [comment]
Issue has been resolved by the below actions (submitted by @rk700) and is mentioned here for documentation purposes.

MuPDF was obviously compiled successfully, but something went wrong when linking the libraries together.
So the **3rd-party libraries shipped with MuPDF** should be used instead.
That is:

1. Uncomment the line https://github.com/rk700/PyMuPDF/blob/master/setup.py#L12. 
2. Comment the line https://github.com/rk700/PyMuPDF/blob/master/setup.py#L15 and https://github.com/rk700/PyMuPDF/blob/master/setup.py#L16,  so that the system-wide libraries would not be linked.
