### ISSUE TITLE
Pages render as black and white only

### ISSUE THREAD

**Issue by jsonjunky** [rk700/PyMuPDF#85]
Hi,
  I try to render a page like so:
` pix = page.getPixmap(matrix=fitz.Identity, colorspace="RGB")
pix.writePNG(key + ".png")
`
But it comes out only as black and white

I do see this error, but have tried many ways to fix it (Ubuntu 16.04) and have not been able to. Not sure if it is related to this issue, but maybe.
`
error: jpeg error: Wrong JPEG library version: library is 80, caller expects 90
warning: read error; treating as end of file
warning: padding truncated image
`

**Comment by JorjMcKie** [comment]
I am not a Linux guy, but until @rk700 has had a look into your issue, you might inspect #69 and make sure that you use all thirdparty software (i.e. esp. JPEG) exactly with the version that MuPDF 1.10a declares to require. It seems to happen, that any version discrepancies here lead to this type of problem. And your error message does point into the same direction.

**Comment by rk700** [comment]
Just as @JorjMcKie has said, it is very likely that the `jpeg` library linked with PyMuPDF is not compatible. 

If you build MuPDF 1.10 from source instead of apt-get, then you could try removing `jpeg` at https://github.com/rk700/PyMuPDF/blob/master/setup.py#L17 and build PyMuPDF again.

Please feel free to contact us if the issue persists.

**Comment by nodejunky** [comment]
Hi, thanks for the response. I suspected that the jpeg library is out of date, but the problem is on Ubuntu 16.04 jpeg8 is the latest version in the repo. I'm not exactly sure how to override this with jpeg9. I did install jpeg 9 directly but it installed alongside jpeg8. I then removed jpeg8 and tried to rebuild mupdf. But it seems ubuntu has dependencies on jpeg8 so the build for mupdf is not seeing that there are two jpeg's and to choose jpeg9 and not jpeg8.

**Comment by jsonjunky** [comment]
Hi, thanks for the response. I suspected that the jpeg library is out of date, but the problem is on Ubuntu 16.04 jpeg8 is the latest version in the repo. I'm not exactly sure how to override this with jpeg9. I did install jpeg 9 directly but it installed alongside jpeg8. I then removed jpeg8 and tried to rebuild mupdf. But it seems ubuntu has dependencies on jpeg8 so the build for mupdf is not seeing that there are two jpeg's and to choose jpeg9 and not jpeg8.

**Comment by jsonjunky** [comment]
Here is the error I see trying to install jpeg9-dev on Ubuntu 16.04
`The following NEW packages will be installed:
  libjpeg9-dev
0 upgraded, 1 newly installed, 0 to remove and 273 not upgraded.
Need to get 0 B/209 kB of archives.
After this operation, 534 kB of additional disk space will be used.
(Reading database ... 290689 files and directories currently installed.)
Preparing to unpack .../libjpeg9-dev_1%3a9b-1ubuntu1_amd64.deb ...
Unpacking libjpeg9-dev:amd64 (1:9b-1ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/libjpeg9-dev_1%3a9b-1ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libjpeg.a', which is also in package libjpeg-turbo8-dev:amd64 1.4.2-0ubuntu3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libjpeg9-dev_1%3a9b-1ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by rk700** [comment]
MuPDF ships all the third party libraries within its source code. So if you build MuPDF from source, then those symbols can also be found in `libmupdfthird.a`:
```
# readelf -s libmupdfthird.a |grep -i jpeg |head
     6: 0000000000000000   912 OBJECT  GLOBAL DEFAULT    4 jpeg_aritab
    14: 0000000000000000    61 FUNC    GLOBAL DEFAULT    5 jpeg_abort
    15: 0000000000000000    33 FUNC    GLOBAL DEFAULT    7 jpeg_destroy
    16: 0000000000000000    29 FUNC    GLOBAL DEFAULT    9 jpeg_alloc_quant_table
    17: 0000000000000000    29 FUNC    GLOBAL DEFAULT   11 jpeg_alloc_huff_table
    25: 0000000000000000   347 FUNC    GLOBAL DEFAULT    5 jpeg_CreateDecompress
    30: 0000000000000000     5 FUNC    GLOBAL DEFAULT    8 jpeg_destroy_decompress
    31: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND jpeg_destroy
    32: 0000000000000000     5 FUNC    GLOBAL DEFAULT   11 jpeg_abort_decompress
    33: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND jpeg_abort
```

If that's the case, then you should link `libmupdfthird.a` instead of `libjpeg.so` when building PyMuPDF. That is, use the third party libraries generated by building MuPDF and leave the system libraries alone. 

Therefore, it's not necessary to remove jpeg8 and install jpeg9.

**Comment by jsonjunky** [comment]
Here's what I tried. 
Build mupdf

> root@lotus:/home/me/PyMuPDF/mupdf# make install
install -d /usr/local/include/mupdf
install -d /usr/local/include/mupdf/fitz
install -d /usr/local/include/mupdf/pdf
install include/mupdf/*.h /usr/local/include/mupdf
install include/mupdf/fitz/*.h /usr/local/include/mupdf/fitz
install include/mupdf/pdf/*.h /usr/local/include/mupdf/pdf
install -d /usr/local/lib
install build/release/libmupdf.a build/release/libmupdfthird.a /usr/local/lib
install -d /usr/local/bin
install build/release/mutool build/release/mupdf-x11  build/release/mupdf-gl build/release/muraster build/release/mujstest build/release/mupdf-x11-curl  /usr/local/bin
install -d /usr/local/share/man/man1
install docs/man/*.1 /usr/local/share/man/man1
install -d /usr/local/share/doc/mupdf
install README COPYING CHANGES docs/*.txt /usr/local/share/doc/mupdf

then

> root@lotus:/home/me/PyMuPDF# python setup.py install
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/fitz-1.10.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/fitz-1.10.0.egg-info

Per the instructions

Then

> root@lotus:/home/me# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> doc = fitz.open("test.pdf") 
>>> page = doc.loadPage(2)
>>> pix = page.getPixmap(matrix = fitz.Identity, colorspace = "RGB")
error: jpeg error: Wrong JPEG library version: library is 80, caller expects 90
warning: read error; treating as end of file
warning: padding truncated image
>>> 

I did remove 'jpeg' from setup.py per a suggestion above. Still produces the error.
I also tried cleaning the project directories before rebuilding.

**Comment by rk700** [comment]
Then how about removing the other third party libraries just as https://github.com/rk700/PyMuPDF/commit/d07f74d21f4114bfafdbc36933b24e6fd5871c15? 

Besides, since MuPDF is installed with prefix `/usr/local/`, the `include_dirs` should set to `/usr/local/include/mupdf` and `library_dirs` should be `/usr/local/lib` in file `setup.py`. And you would see something like `gcc ... -L/usr/local/lib -lmupdf -lmupdfthird -o ...` when building PyMuPDF.

After building PyMuPDF, you could take a look at the file `_fitz.so` with command `ldd _fitz.so`, which would print the its dependencies. If the third party libraries in the system default path are still used, then we may need to figure out what happened during linking.

**Comment by JorjMcKie** [comment]
@jsonjunky - any news from your side? This issue is becoming stale, and we would certainly like to know if your problem is solved ...
