### ISSUE TITLE
Problem: adding two ToC entries to the last page of a PDF file

### ISSUE THREAD

**Issue by o-xylene** [rk700/PyMuPDF#86]
Hi,
I want to add table of contents to a PDF file by using `setToC()` , but I got `ValueError` when I add two entries to the last page.
It works fine when adding multiple entries to other pages besides the last page and adding only one entry to the last page.
Is there a limit on the last page or I am using `setToc()` in the wrong way ?
Thank you.

Example:
```python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> pdf = fitz.open("2page.pdf")
>>> pdf.pageCount
2
>>> pdf.setToC([ [1, "first", 1], [2, "second", 1] ])
2
>>> pdf.getToC()
[[1, 'first', 1], [2, 'second', 1]]
>>> pdf.setToC([ [1, "first", 2] ])
1
>>> pdf.getToC()
[[1, 'first', 2]]
>>> pdf.setToC([ [1, "first", 2], [2, "second", 2] ])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\fitz\utils.py", line 757, in setToC
    raise ValueError("row %s:page number out of range" % (str(i),))
ValueError: row 0:page number out of range
```

**Comment by JorjMcKie** [comment]
@o-xylene - fyi: confirming the issue - starting investigation ...

**Comment by JorjMcKie** [comment]
@o-xylene - I think I already found the error: a stupid mistake.
Thanks for reporting this!

Solution:
----------
In `utils.py` line number 756 now reads:

        if not -1 <= t1[2] < pageCount:

But it should be:

        if not -1 <= t1[2] <= pageCount:

because page numbers in TOC lists are 1-based.
This error indeed only occurs, when more than one bookmark point to the last page.

What is your preference:
-------------------------
You can do a quick fix and change `utils.py` directly as described, or wait until I have created a new general fix. May take a day, because I am working on new functionality (ability to edit the links of a PDF ...) and therefore need to get hold of a previous version.

I assume you have been using binary installs on your Windows system?

**Comment by JorjMcKie** [comment]
@o-xylene - have you noticed? I have uploaded a bugfix.
Please check if your issue is solved.

**Comment by o-xylene** [comment]
It's solved. Thank you.
