### ISSUE TITLE
PyMuPDF with Tkinter: 

### ISSUE THREAD

**Issue by rbolado** [rk700/PyMuPDF#91]
Hi there,

I am trying to run PyMuPDF with Tkinter. I am following the default examples shown here. I am using python 3.5 (windows 7 64-bits). When I run 

> Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

I am getting the following error:

> s = d.decode(data)
TypeError: argument 1 must be read-only bytes-like object, not bytearray

Any help would be great?

Many thanks,

**Comment by JorjMcKie** [comment]
Hi @rbolado,
don't quite understand yet ...

* pix.samples is a bytearray, why should you want to decode it? 
* the line getting the error (`s = d.decode ...`)  - in what context is it with the Ìmage.frombytes...`?

What you anyway always could do, is taking `bytes(pix.samples)` instead of `pix.samples` directly ...

Please do keep me in the loop. Maybe show a more complete part of the script?

**Comment by JorjMcKie** [comment]
@rbolado - just confirmed your error:

You are right - you **must** do the following:
`img = Image.frombytes("RGB", [pix.width, pix.height], bytes(pix.samples))`

I will adjust the PyMuPDF accordingly ...

**Comment by JorjMcKie** [comment]
I will also check, whether we should change PyMuPDF to provide `pix.samples` as a `bytes` object from the start. Would have to make sure that this won't break existing code.

**Comment by rbolado** [comment]
Hi JorjMcKie,

Many thanks for your help. It is now working ok!

Thanks

**Comment by JorjMcKie** [comment]
Great to hear that!

**Comment by JorjMcKie** [comment]
@rk700
I know `type(pix.samples)` is bytearray to ensure compatibility across Py2 & Py3.

Do you remember why we did not choose `bytes` from the beginning? Maybe it was prior to Python 2.6, where the equivalence between PyBytes and PyString was introduced?

And do you see any obstacle to change pix.samples to bytes right away?

**Comment by rk700** [comment]
Sorry but I cannot remember why I chose `bytearray` instead of `bytes`. I just did some search and it seems that `bytearray` is mutable while `bytes` is not. So it should be fine to make a change as long as `Pixmap.samples` is read only.

**Comment by JorjMcKie** [comment]
Ok, fine, thank you.
I will go ahead and change pix.samples to bytes then. This will ensure it is handled as a read-only object in both, Python 2 and Python 3.

Von: Ruikai Liu [mailto:notifications@github.com]
Gesendet: Sonntag, 23. April 2017 21:24
An: rk700/PyMuPDF <PyMuPDF@noreply.github.com>
Cc: Jorj X. McKie <jorj.x.mckie@outlook.de>; State change <state_change@noreply.github.com>
Betreff: Re: [rk700/PyMuPDF] PyMuPDF with Tkinter: (#91)


Sorry but I cannot remember why I chose bytearray instead of bytes. I just did some search and it seems that bytearray is mutable while bytes is not. So it should be fine to make a change as long as Pixmap.samples is read only.
